apiVersion: v1
kind: Pod
metadata:
  name: todoapp
  namespace: todoapp
  labels:
    app: todoapp
spec:
  containers:
  - name: todoapp
    image: adryga/todoapp:3.0.0
    ports:
    - containerPort: 8080
livenessProbe:
  httpGet:
    path: /api/health/liveness/
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /api/health/readiness/
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5